; PlatformIO Project Configuration File
; CheatSheet2 — ESP32-S3-N16R8 CAM + ST7789 TFT

[env:esp32-s3-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_build.filesystem = littlefs

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -DLV_LVGL_H_INCLUDE_SIMPLE

    ; --- LVGL ---
    -DLV_CONF_INCLUDE_SIMPLE

extra_scripts = pre:scripts/copy_lv_conf.py

lib_deps =
    lvgl/lvgl@^9.2
    bodmer/TFT_eSPI@^2.5.43
    bitbank2/JPEGDEC@^1.4.0
monitor_filters = esp32_exception_decoder